export const data={
  "educational":[
        {
            "id":"educational1",
            "image":"pullingcart1.jpg",
            "title":"Telescope1",
            "price":"1500",
            "total":"1500",
            "quantity":1
        },
        {
            "id":"educational2",
            "image":"telescope1.jpg",
            "title":"Telescope2",
            "price":"1500",
            "total":"1500",
            "quantity":1
        },
        {
            "id":"educational3",
            "image":"telescope1.jpg",
            "title":"Telescope",
            "price":"1500",
            "total":"1500",
            "quantity":1
        },
        {
            "id":"educational4",
            "image":"telescope1.jpg",
            "title":"Telescope",
            "price":"1500",
            "total":"1500",
            "quantity":1
        }
      ],
      "actions":[
        {
            "id":"action1",
            "image":"telescope1.jpg",
            "title":"Telescope",
            "price":"1500",
            "total":"1500",
            "quantity":1
        },
        {
            "id":"educational2",
            "image":"telescope1.jpg",
            "title":"Telescope",
            "price":"1500",
            "total":"1500",
            "quantity":1
        },
        {
            "id":"educational3",
            "image":"telescope1.jpg",
            "title":"Telescope",
            "price":"1500",
            "total":"1500",
            "quantity":1
        },
        {
            "id":"educational4",
            "image":"telescope1.jpg",
            "title":"Telescope",
            "price":"1500",
            "total":"1500",
            "quantity":1
        }

      ],
      "Dolls":[
        {
            "id":"dolls1",
            "image":"telescope1.jpg",
            "title":"Telescope",
            "price":"1500",
            "total":"1500",
            "quantity":1
        },
        {
            "id":"educational2",
            "image":"telescope1.jpg",
            "title":"Telescope",
            "price":"1500",
            "total":"1500",
            "quantity":1
        },
        {
            "id":"educational3",
            "image":"telescope1.jpg",
            "title":"Telescope",
            "price":"1500",
            "total":"1500",
            "quantity":1
        },
        {
            "id":"educational4",
            "image":"telescope1.jpg",
            "title":"Telescope",
            "price":"1500",
            "total":"1500",
            "quantity":1
        }

      ],
      "electronic":[
        {
            "id":"electronic1",
            "image":"telescope1.jpg",
            "title":"Telescope",
            "price":"1500",
            "total":"1500",
            "quantity":1
        },
        {
            "id":"educational2",
            "image":"telescope1.jpg",
            "title":"Telescope",
            "price":"1500",
            "total":"1500",
            "quantity":1
        },
        {
            "id":"educational3",
            "image":"telescope1.jpg",
            "title":"Telescope",
            "price":"1500",
            "total":"1500",
            "quantity":1
        },
        {
            "id":"educational4",
            "image":"telescope1.jpg",
            "title":"Telescope",
            "price":"1500",
            "total":"1500",
            "quantity":1
        }

      ],
      "animals":[
        {
            "id":"animals1",
            "image":"telescope1.jpg",
            "title":"Telescope",
            "price":"1500",
            "total":"1500",
            "quantity":1
        },
        {
            "id":"educational2",
            "image":"telescope1.jpg",
            "title":"Telescope",
            "price":"1500",
            "total":"1500",
            "quantity":1
        },
        {
            "id":"educational3",
            "image":"telescope1.jpg",
            "title":"Telescope",
            "price":"1500",
            "total":"1500",
            "quantity":1
        },
        {
            "id":"educational4",
            "image":"telescope1.jpg",
            "title":"Telescope",
            "price":"1500",
            "total":"1500",
            "quantity":1
        }

      ] , "mp":[
          {
              "bcolor":"red",
              "image":"mp1.jpg",
              "title":"Helicopter",
              "col":"green"

          },
          {
            "bcolor":"green",
            "image":"mp2.jpg",
            "title":"Cube",
            "col":"blue"
            
        },
        {
            "bcolor":"blue",
            "image":"mp3.jpg",
            "title":"Toy car",
            "col":"yellow"
            
        },
        {
            "bcolor":"orange",
            "image":"mp4.jpg",
            "title":"Wooden horse",
            "col":"red"
            
        }
      ]
}